### ISSUE TITLE
Consider using inputDeviceCapabilities API

### ISSUE THREAD

**Issue by RByers** [rafrex/detect-it#1]
Chrome supports the [InputDeviceCapabilities API](http://wicg.github.io/InputDeviceCapabilities/) which tries to solve some of the issues here.  Worth using when it's supported?  Other vendors have indicated support for the idea, but are waiting to see if there's adoption before implementing.

**Comment by rafrex** [comment]
@RByers The InputDevicesCapabilities API looks interesting. Just spent some time playing around with it... but I couldn't figure out how to use it to help Detect It determine the device type (maybe I'm missing something). I can see how it would be useful in event handler functions, but how do I use it to determine capabilities of the device prior to setting event listeners?

I tried `new window.InputDeviceCapabilities()` but always got the object `{firesTouchEvents: false}` even on Chrome v54 on my Nexus.

Also, is there a way to get info about if the device has a mouse or if it's touch only?

On another note, `'InputDeviceCapabilities' in window` and `'sourceCapabilities' in UIEvent.prototype`, both failed on Chrome v54 on iOS 10 and Chrome v52 on a Windows 10 hybrid. Is it not supported yet in Chrome on those devices?

**Comment by RByers** [comment]
> but how do I use it to determine capabilities of the device prior to setting event listeners?

Yep, you can't (the media queries you're already relying on are for that use case).  This is for the case of responding to different input devices correctly.  So maybe it doesn't apply to your case.

> Also, is there a way to get info about if the device has a mouse or if it's touch only?

Just `pointer`/`any-pointer` that you're already using.

> On another note, 'InputDeviceCapabilities' in window and 'sourceCapabilities' in UIEvent.prototype, both failed on Chrome v54 on iOS 10 and Chrome v52 on a Windows 10 hybrid. Is it not supported yet in Chrome on those devices?

Browsers on iOS are [basically all Safari under the covers](http://thenextweb.com/apple/2013/04/04/will-chrome-for-ios-be-able-to-use-googles-new-browser-rendering-engine-blink/) so nothing we can do there.   But that definitely should succeed on Chrome 47+ on Windows.  I [tested](http://output.jsbin.com/riloko) Chrome 50 on Windows ([via browserstack](https://www.browserstack.com/screenshots/c800e9c306a233fd5ae97a80f6c8f4ad615e9c45)) and verified it was working there.

**Comment by RByers** [comment]
BTW sorry I didn't look more carefully at what you're doing.  If you really want to predict devices in advance of any input events, then relying on the media queries is absolutely the right thing to do (and you can close this bug).  But be aware that that often isn't as useful as people expect - lots of devices have a touchscreen that the user never touches (touch laptops, windows machines with virtual touchscreen drivers for testing), or are primarily touch devices with also some mouse capability (eg. blackberry phones with a trackball) and touchscreens and mice can of course come and go during the lifetime of page.

**Comment by rafrex** [comment]
@RByers no worries, I hadn't heard of the InputDevicesCapabilities API, so I learned something new! Also, I re-checked it on Windows and it works, must have had a typo before or something, whoops.
